FROM mcr.microsoft.com/windows/server:ltsc2022
WORKDIR /
 
# Set default shell to PowerShell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 
# Install chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
 
# Set default confirmation value to yes
RUN choco feature enable -n allowGlobalConfirmation

# Install VS build tools and other workloads
RUN choco install \
    visualstudio2022buildtools \
    visualstudio2022testagent \
    visualstudio2022-workload-azurebuildtools \
    visualstudio2022-workload-manageddesktopbuildtools \
    visualstudio2022-workload-nodebuildtools \
    visualstudio2022-workload-webbuildtools \
    visualstudio2022-workload-vctools

# Install VS 2019 build tools 
RUN choco install visualstudio2019buildtools
 
# Install .NET Framework 3.5, 3.0, 2.0
RUN choco install dotnet3.5

# Install .NET Framework 4.0 dev packs
RUN choco install netfx-4.6.2-devpack
 
# Install custom ST dependencies
RUN choco install advanced-installer --version 21.3.1; \
    setx AdvancedInstaller 'C:\Program Files (x86)\Caphyon\Advanced Installer 21.3.1\bin\x86\AdvancedInstaller.com' /M

RUN choco install dotnetreactor --version 6.9.0.0 --ignore-checksums

COPY PureComponents_NETWinFormsSuite_V2011.msi .
RUN Start-Process msiexec.exe -Wait -ArgumentList '/I PureComponents_NETWinFormsSuite_V2011.msi /quiet'
RUN Remove-Item PureComponents_NETWinFormsSuite_V2011.msi

RUN choco install 7zip.install

# Start the Azure DevOps agent
COPY start.ps1 .
RUN mkdir azp
CMD powershell -ExecutionPolicy Unrestricted .\start.ps1
