FROM mcr.microsoft.com/windows/servercore:ltsc2022
WORKDIR /
 
# Set default shell to PowerShell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 
# Install chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
 
# Set default confirmation value to yes
RUN choco feature enable -n allowGlobalConfirmation

# Install all Chocolatey packages in one command (parallelized)
RUN choco install --parallel \
    visualstudio2026buildtools \
    visualstudio2026testagent \
    visualstudio2026-workload-azurebuildtools \
    visualstudio2026-workload-manageddesktopbuildtools \
    visualstudio2026-workload-nodebuildtools \
    visualstudio2026-workload-webbuildtools \
    visualstudio2026-workload-vctools \
    netfx-4.5.2-devpack \
    netfx-4.6.2-devpack \
    dotnet-6.0-sdk-4xx \
    dotnet-8.0-sdk-3xx \
    dotnet-10.0-sdk \
    7zip.install \
    msbuild.communitytasks

RUN choco install advanced-installer --version 22.0; \
    setx AdvancedInstaller 'C:\Program Files (x86)\Caphyon\Advanced Installer 22.0\bin\x86\AdvancedInstaller.com' /M

RUN choco install dotnetreactor --version 6.9.0.0 --ignore-checksums

COPY PureComponents_NETWinFormsSuite_V2011.msi .
RUN Start-Process msiexec.exe -Wait -ArgumentList '/I PureComponents_NETWinFormsSuite_V2011.msi /quiet'
RUN Remove-Item PureComponents_NETWinFormsSuite_V2011.msi

# Start the Azure DevOps agent
COPY start.ps1 .
RUN mkdir azp
CMD powershell -ExecutionPolicy Unrestricted .\start.ps1
