name: publish dotnet framework

on:
  push:
    branches:
    - master
    paths:
    - 'DotNetFramework/**'

jobs:
  publish-dotnet-core-agent-image:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the dotnetframework-azure-devops-agent Docker image
      run: |
        docker build DotNetFramework --tag ghcr.io/redevltd/dotnetframework-azure-devops-agent:latest        
        docker push ghcr.io/redevltd/dotnetframework-azure-devops-agent:latest
