name: publish Windows Office

on:
  push:
    branches:
    - master
    paths:
    - 'WindowsOffice/**'

jobs:
  publish-windows-office-agent-image:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the windows-office-azure-devops-agent Docker image
      run: |
        docker build WindowsOffice --tag ghcr.io/redevltd/windows-office-azure-devops-agent:latest        
        docker push ghcr.io/redevltd/windows-office-azure-devops-agent:latest
