name: publish

on:
  push:
    branches:
    - master

jobs:
  publish-android-sdk-azure-devops-agent-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the android-sdk-azure-devops-agent Docker image
      run: |
        docker build DotNetCore --tag ghcr.io/redevltd/dotnetcore-azure-devops-agent:latest        
        docker push ghcr.io/redevltd/dotnetcore-azure-devops-agent:latest
